#!/usr/bin/zsh

# Making my Mac truly mine :')

# Remove Message of the day prompt
touch $HOME/.hushlogin

SCREENSHOT_FOLDER=~/Pictures/Screenshots

mkdir -p $SCREENSHOT_FOLDER

# Set the default file format for screenshots to png
defaults write com.apple.screencapture type png

# Set default screenshot location to a specific folder
defaults write com.apply.screencapture location $SCREENSHOT_FOLDER

# Show hidden files by default in the Finder
defaults write com.apple.finder AppleShowAllFiles -bool TRUE

# Remove all default apps from Dock and reload it
defaults write com.apple.dock persistent-apps -array; killall Dock

# Unhide the $HOME/Library directory
chflags nohidden "~/Library"

# Show Finder path bar
defaults write com.apple.finder ShowPathbar -bool true

# Show Finder status bar
defaults write com.apple.finder ShowStatusBar -bool true